import java_cup.runtime.*;
import java.io.*;
import java.util.function.Supplier;
import java.util.Map;       
import java.util.HashMap;   

parser code {:
    scanner s;
    parser(scanner s){ this.s=s; }
    public Map<String, Integer> variaveis = new HashMap<>();
:}

scan with {: return s.next_token(); :};

terminal SEMI, PLUS, MINUS, TIMES, DIV, LPAREN, RPAREN, LBRACE, RBRACE;
terminal EQUAL, NOTEQUAL, BIGGER, MINER, BIGGEREQ, MINEREQ, UMINUS;
terminal AND, OR, NOT;
terminal IF, ELSE, WHILE, RETURN, PRINT;
terminal ASSIGN; 
terminal String ID;  
terminal Integer NUMBER;

non terminal                  expr_list;
non terminal Supplier<Integer> expr; 
non terminal Runnable          stmt;
non terminal Runnable          stmt_list;
non terminal Runnable          block;
non terminal Runnable          body;

precedence right ASSIGN;
precedence right ELSE; 
precedence left OR;
precedence left AND;
precedence left EQUAL, NOTEQUAL, BIGGER, MINER, BIGGEREQ, MINEREQ;
precedence left PLUS, MINUS;
precedence left TIMES, DIV;
precedence left NOT, UMINUS;

// --- REGRAS GRAMATICAIS ---

expr_list ::= expr_list stmt:s  {: s.run(); :}
            | stmt:s            {: s.run(); :}
            ;

stmt_list ::= stmt_list:sl stmt:s 
              {: RESULT = () -> { sl.run(); s.run(); }; :}
            | stmt:s
              {: RESULT = s; :}
            ;

block ::= LBRACE stmt_list:sl RBRACE
          {: RESULT = sl; :}
        ;

body ::= stmt:s   {: RESULT = s; :}
       | block:b  {: RESULT = b; :}
       ;

stmt ::= 
      IF LPAREN expr:cond RPAREN body:b1
      {: 
         RESULT = () -> {
             if (cond.get() == 1) {
                 b1.run();
             }
         };
      :}
      
    | IF LPAREN expr:cond RPAREN body:b1 ELSE body:b2
      {: 
         RESULT = () -> {
             if (cond.get() == 1) {
                 b1.run();
             } else {
                 b2.run();
             }
         };
      :}
      
    | PRINT expr:e SEMI
      {:
         RESULT = () -> {
             System.out.println(">> " + e.get());
         };
      :}

    | WHILE LPAREN expr:cond RPAREN body:b1
      {: 
         RESULT = () -> {
             while (cond.get() == 1) {
                 b1.run();
             }
         };
      :}

    | RETURN expr:e SEMI
      {:
         RESULT = () -> {
             System.out.println(">>> PROSPEROU: " + e.get());
         };
      :}
      
    | expr:e SEMI 
      {: 
         RESULT = () -> {
             System.out.println("Resultado: " + e.get());
         };
      :}

    | ID:nome ASSIGN expr:e SEMI
      {: 
         RESULT = () -> {
             int valor = e.get(); 
             parser.variaveis.put(nome, valor); 
             System.out.println("> " + nome + " agora e " + valor + "!");
         };
      :}
    ;

// --- REGRAS DE EXPRESSÃO ---
expr      ::= expr:e1 PLUS  expr:e2         {: RESULT = () -> e1.get() + e2.get(); :}
             | expr:e1 MINUS expr:e2        {: RESULT = () -> e1.get() - e2.get(); :}
             | expr:e1 TIMES expr:e2        {: RESULT = () -> e1.get() * e2.get(); :}
             | expr:e1 DIV expr:e2          {: RESULT = () -> { try { return e1.get() / e2.get(); } catch (ArithmeticException ex) { System.err.println("Erro: Divisao por zero! Nao desista, revise sua estrategia!"); return 0; } }; :}
             | expr:e1 BIGGER expr:e2       {: RESULT = () -> (e1.get() > e2.get()) ? 1 : 0; :}
             | expr:e1 MINER expr:e2        {: RESULT = () -> (e1.get() < e2.get()) ? 1 : 0; :}
             | expr:e1 BIGGEREQ expr:e2     {: RESULT = () -> (e1.get() >= e2.get()) ? 1 : 0; :}
             | expr:e1 MINEREQ expr:e2      {: RESULT = () -> (e1.get() <= e2.get()) ? 1 : 0; :}
             | expr:e1 EQUAL expr:e2        {: RESULT = () -> e1.get().equals(e2.get()) ? 1 : 0; :}
             | expr:e1 NOTEQUAL expr:e2     {: RESULT = () -> e1.get().equals(e2.get()) ? 0 : 1; :}
             | expr:e1 AND expr:e2          {: RESULT = () -> (e1.get() != 0 && e2.get() != 0) ? 1 : 0; :}
             | expr:e1 OR expr:e2           {: RESULT = () -> (e1.get() != 0 || e2.get() != 0) ? 1 : 0; :}
             | NOT expr:e                   {: RESULT = () -> (e.get() == 0) ? 1 : 0; :} %prec NOT
             | MINUS expr:e                 {: RESULT = () -> -e.get(); :} %prec UMINUS
             | LPAREN expr:e RPAREN         {: RESULT = () -> e.get(); :}
             | NUMBER:n                     {: RESULT = () -> n; :}
             | ID:nome
               {: 
                  RESULT = () -> {
                      if (parser.variaveis.containsKey(nome)) {
                          return parser.variaveis.get(nome);
                      } else {
                          System.err.println("Erro: Variavel '" + nome + "' nao foi declarada! Visualize seu objetivo e tente novamente.");
                          return 0; 
                      }
                  };
               :}
             ;
