
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.function.Supplier;
import java.util.Map;
import java.util.HashMap;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\040\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\005\004\000\002\005\003\000\002\006\005" +
    "\000\002\007\003\000\002\007\003\000\002\004\007\000" +
    "\002\004\011\000\002\004\005\000\002\004\007\000\002" +
    "\004\005\000\002\004\004\000\002\004\006\000\002\003" +
    "\005\000\002\003\005\000\002\003\005\000\002\003\005" +
    "\000\002\003\005\000\002\003\005\000\002\003\005\000" +
    "\002\003\005\000\002\003\005\000\002\003\005\000\002" +
    "\003\005\000\002\003\005\000\002\003\004\000\002\003" +
    "\004\000\002\003\005\000\002\003\003\000\002\003\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\105\000\024\006\004\011\017\026\014\027\011\031" +
    "\005\032\016\033\013\035\012\036\010\001\002\000\014" +
    "\006\004\011\017\026\014\035\020\036\010\001\002\000" +
    "\004\011\103\001\002\000\026\002\uffff\006\uffff\011\uffff" +
    "\026\uffff\027\uffff\031\uffff\032\uffff\033\uffff\035\uffff\036" +
    "\uffff\001\002\000\026\002\102\006\004\011\017\026\014" +
    "\027\011\031\005\032\016\033\013\035\012\036\010\001" +
    "\002\000\036\004\uffe3\005\uffe3\006\uffe3\007\uffe3\010\uffe3" +
    "\012\uffe3\015\uffe3\016\uffe3\017\uffe3\020\uffe3\021\uffe3\022" +
    "\uffe3\024\uffe3\025\uffe3\001\002\000\004\011\064\001\002" +
    "\000\036\004\uffe2\005\uffe2\006\uffe2\007\uffe2\010\uffe2\015" +
    "\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022\uffe2\024\uffe2" +
    "\025\uffe2\034\061\001\002\000\014\006\004\011\017\026" +
    "\014\035\020\036\010\001\002\000\014\006\004\011\017" +
    "\026\014\035\020\036\010\001\002\000\034\004\055\005" +
    "\027\006\022\007\035\010\033\015\026\016\025\017\024" +
    "\020\032\021\030\022\031\024\023\025\036\001\002\000" +
    "\014\006\004\011\017\026\014\035\020\036\010\001\002" +
    "\000\014\006\004\011\017\026\014\035\020\036\010\001" +
    "\002\000\036\004\uffe2\005\uffe2\006\uffe2\007\uffe2\010\uffe2" +
    "\012\uffe2\015\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022" +
    "\uffe2\024\uffe2\025\uffe2\001\002\000\034\005\027\006\022" +
    "\007\035\010\033\012\034\015\026\016\025\017\024\020" +
    "\032\021\030\022\031\024\023\025\036\001\002\000\014" +
    "\006\004\011\017\026\014\035\020\036\010\001\002\000" +
    "\014\006\004\011\017\026\014\035\020\036\010\001\002" +
    "\000\014\006\004\011\017\026\014\035\020\036\010\001" +
    "\002\000\014\006\004\011\017\026\014\035\020\036\010" +
    "\001\002\000\014\006\004\011\017\026\014\035\020\036" +
    "\010\001\002\000\014\006\004\011\017\026\014\035\020" +
    "\036\010\001\002\000\014\006\004\011\017\026\014\035" +
    "\020\036\010\001\002\000\014\006\004\011\017\026\014" +
    "\035\020\036\010\001\002\000\014\006\004\011\017\026" +
    "\014\035\020\036\010\001\002\000\014\006\004\011\017" +
    "\026\014\035\020\036\010\001\002\000\036\004\uffe4\005" +
    "\uffe4\006\uffe4\007\uffe4\010\uffe4\012\uffe4\015\uffe4\016\uffe4" +
    "\017\uffe4\020\uffe4\021\uffe4\022\uffe4\024\uffe4\025\uffe4\001" +
    "\002\000\014\006\004\011\017\026\014\035\020\036\010" +
    "\001\002\000\014\006\004\011\017\026\014\035\020\036" +
    "\010\001\002\000\036\004\uffe7\005\027\006\022\007\035" +
    "\010\033\012\uffe7\015\026\016\025\017\024\020\032\021" +
    "\030\022\031\024\023\025\uffe7\001\002\000\036\004\ufff0" +
    "\005\ufff0\006\ufff0\007\ufff0\010\ufff0\012\ufff0\015\ufff0\016" +
    "\ufff0\017\ufff0\020\ufff0\021\ufff0\022\ufff0\024\ufff0\025\ufff0" +
    "\001\002\000\036\004\uffef\005\uffef\006\uffef\007\uffef\010" +
    "\uffef\012\uffef\015\uffef\016\uffef\017\uffef\020\uffef\021\uffef" +
    "\022\uffef\024\uffef\025\uffef\001\002\000\036\004\uffed\005" +
    "\027\006\022\007\035\010\033\012\uffed\015\uffed\016\uffed" +
    "\017\uffed\020\uffed\021\uffed\022\uffed\024\uffed\025\uffed\001" +
    "\002\000\036\004\uffeb\005\027\006\022\007\035\010\033" +
    "\012\uffeb\015\uffeb\016\uffeb\017\uffeb\020\uffeb\021\uffeb\022" +
    "\uffeb\024\uffeb\025\uffeb\001\002\000\036\004\uffec\005\027" +
    "\006\022\007\035\010\033\012\uffec\015\uffec\016\uffec\017" +
    "\uffec\020\uffec\021\uffec\022\uffec\024\uffec\025\uffec\001\002" +
    "\000\036\004\ufff2\005\ufff2\006\ufff2\007\035\010\033\012" +
    "\ufff2\015\ufff2\016\ufff2\017\ufff2\020\ufff2\021\ufff2\022\ufff2" +
    "\024\ufff2\025\ufff2\001\002\000\036\004\uffea\005\027\006" +
    "\022\007\035\010\033\012\uffea\015\uffea\016\uffea\017\uffea" +
    "\020\uffea\021\uffea\022\uffea\024\uffea\025\uffea\001\002\000" +
    "\036\004\uffe9\005\027\006\022\007\035\010\033\012\uffe9" +
    "\015\uffe9\016\uffe9\017\uffe9\020\uffe9\021\uffe9\022\uffe9\024" +
    "\uffe9\025\uffe9\001\002\000\036\004\uffee\005\027\006\022" +
    "\007\035\010\033\012\uffee\015\uffee\016\uffee\017\uffee\020" +
    "\uffee\021\uffee\022\uffee\024\uffee\025\uffee\001\002\000\036" +
    "\004\uffe8\005\027\006\022\007\035\010\033\012\uffe8\015" +
    "\026\016\025\017\024\020\032\021\030\022\031\024\uffe8" +
    "\025\uffe8\001\002\000\036\004\ufff1\005\ufff1\006\ufff1\007" +
    "\035\010\033\012\ufff1\015\ufff1\016\ufff1\017\ufff1\020\ufff1" +
    "\021\ufff1\022\ufff1\024\ufff1\025\ufff1\001\002\000\034\004" +
    "\054\005\027\006\022\007\035\010\033\015\026\016\025" +
    "\017\024\020\032\021\030\022\031\024\023\025\036\001" +
    "\002\000\032\002\ufff5\006\ufff5\011\ufff5\014\ufff5\026\ufff5" +
    "\027\ufff5\030\ufff5\031\ufff5\032\ufff5\033\ufff5\035\ufff5\036" +
    "\ufff5\001\002\000\032\002\ufff4\006\ufff4\011\ufff4\014\ufff4" +
    "\026\ufff4\027\ufff4\030\ufff4\031\ufff4\032\ufff4\033\ufff4\035" +
    "\ufff4\036\ufff4\001\002\000\036\004\uffe6\005\uffe6\006\uffe6" +
    "\007\uffe6\010\uffe6\012\uffe6\015\uffe6\016\uffe6\017\uffe6\020" +
    "\uffe6\021\uffe6\022\uffe6\024\uffe6\025\uffe6\001\002\000\034" +
    "\004\060\005\027\006\022\007\035\010\033\015\026\016" +
    "\025\017\024\020\032\021\030\022\031\024\023\025\036" +
    "\001\002\000\032\002\ufff7\006\ufff7\011\ufff7\014\ufff7\026" +
    "\ufff7\027\ufff7\030\ufff7\031\ufff7\032\ufff7\033\ufff7\035\ufff7" +
    "\036\ufff7\001\002\000\014\006\004\011\017\026\014\035" +
    "\020\036\010\001\002\000\034\004\063\005\027\006\022" +
    "\007\035\010\033\015\026\016\025\017\024\020\032\021" +
    "\030\022\031\024\023\025\036\001\002\000\032\002\ufff3" +
    "\006\ufff3\011\ufff3\014\ufff3\026\ufff3\027\ufff3\030\ufff3\031" +
    "\ufff3\032\ufff3\033\ufff3\035\ufff3\036\ufff3\001\002\000\014" +
    "\006\004\011\017\026\014\035\020\036\010\001\002\000" +
    "\034\005\027\006\022\007\035\010\033\012\066\015\026" +
    "\016\025\017\024\020\032\021\030\022\031\024\023\025" +
    "\036\001\002\000\026\006\004\011\017\013\067\026\014" +
    "\027\011\031\005\032\016\033\013\035\012\036\010\001" +
    "\002\000\024\006\004\011\017\026\014\027\011\031\005" +
    "\032\016\033\013\035\012\036\010\001\002\000\032\002" +
    "\ufffb\006\ufffb\011\ufffb\014\ufffb\026\ufffb\027\ufffb\030\ufffb" +
    "\031\ufffb\032\ufffb\033\ufffb\035\ufffb\036\ufffb\001\002\000" +
    "\032\002\ufffa\006\ufffa\011\ufffa\014\ufffa\026\ufffa\027\ufffa" +
    "\030\ufffa\031\ufffa\032\ufffa\033\ufffa\035\ufffa\036\ufffa\001" +
    "\002\000\032\002\ufff9\006\ufff9\011\ufff9\014\ufff9\026\ufff9" +
    "\027\ufff9\030\073\031\ufff9\032\ufff9\033\ufff9\035\ufff9\036" +
    "\ufff9\001\002\000\026\006\004\011\017\013\067\026\014" +
    "\027\011\031\005\032\016\033\013\035\012\036\010\001" +
    "\002\000\032\002\ufff8\006\ufff8\011\ufff8\014\ufff8\026\ufff8" +
    "\027\ufff8\030\ufff8\031\ufff8\032\ufff8\033\ufff8\035\ufff8\036" +
    "\ufff8\001\002\000\026\006\ufffd\011\ufffd\014\ufffd\026\ufffd" +
    "\027\ufffd\031\ufffd\032\ufffd\033\ufffd\035\ufffd\036\ufffd\001" +
    "\002\000\026\006\004\011\017\014\100\026\014\027\011" +
    "\031\005\032\016\033\013\035\012\036\010\001\002\000" +
    "\026\006\ufffe\011\ufffe\014\ufffe\026\ufffe\027\ufffe\031\ufffe" +
    "\032\ufffe\033\ufffe\035\ufffe\036\ufffe\001\002\000\032\002" +
    "\ufffc\006\ufffc\011\ufffc\014\ufffc\026\ufffc\027\ufffc\030\ufffc" +
    "\031\ufffc\032\ufffc\033\ufffc\035\ufffc\036\ufffc\001\002\000" +
    "\026\002\001\006\001\011\001\026\001\027\001\031\001" +
    "\032\001\033\001\035\001\036\001\001\002\000\004\002" +
    "\000\001\002\000\014\006\004\011\017\026\014\035\020" +
    "\036\010\001\002\000\034\005\027\006\022\007\035\010" +
    "\033\012\105\015\026\016\025\017\024\020\032\021\030" +
    "\022\031\024\023\025\036\001\002\000\026\006\004\011" +
    "\017\013\067\026\014\027\011\031\005\032\016\033\013" +
    "\035\012\036\010\001\002\000\032\002\ufff6\006\ufff6\011" +
    "\ufff6\014\ufff6\026\ufff6\027\ufff6\030\ufff6\031\ufff6\032\ufff6" +
    "\033\ufff6\035\ufff6\036\ufff6\001\002\000\036\004\uffe5\005" +
    "\uffe5\006\uffe5\007\uffe5\010\uffe5\012\uffe5\015\uffe5\016\uffe5" +
    "\017\uffe5\020\uffe5\021\uffe5\022\uffe5\024\uffe5\025\uffe5\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\105\000\010\002\006\003\014\004\005\001\001\000" +
    "\004\003\106\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\014\004\100\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\056\001\001" +
    "\000\004\003\055\001\001\000\002\001\001\000\004\003" +
    "\052\001\001\000\004\003\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\051\001\001\000\004\003" +
    "\050\001\001\000\004\003\047\001\001\000\004\003\046" +
    "\001\001\000\004\003\045\001\001\000\004\003\044\001" +
    "\001\000\004\003\043\001\001\000\004\003\042\001\001" +
    "\000\004\003\041\001\001\000\004\003\040\001\001\000" +
    "\002\001\001\000\004\003\037\001\001\000\004\003\036" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\061" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\003" +
    "\064\001\001\000\002\001\001\000\012\003\014\004\067" +
    "\006\070\007\071\001\001\000\010\003\014\004\074\005" +
    "\075\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\003\014\004\067\006\070\007\073\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\003\014" +
    "\004\076\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\103\001\001" +
    "\000\002\001\001\000\012\003\014\004\067\006\070\007" +
    "\105\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.next_token(); 
    }


    scanner s;
    parser(scanner s){ this.s=s; }
    public Map<String, Integer> variaveis = new HashMap<>();


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // expr_list ::= expr_list stmt 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 s.run(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= expr_list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr_list ::= stmt 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 s.run(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmt_list ::= stmt_list stmt 
            {
              Runnable RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Runnable sl = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> { sl.run(); s.run(); }; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmt_list ::= stmt 
            {
              Runnable RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // block ::= LBRACE stmt_list RBRACE 
            {
              Runnable RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Runnable sl = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = sl; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("block",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // body ::= stmt 
            {
              Runnable RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("body",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // body ::= block 
            {
              Runnable RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable b = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = b; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("body",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= IF LPAREN expr RPAREN body 
            {
              Runnable RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> cond = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int b1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int b1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable b1 = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
         RESULT = () -> {
             if (cond.get() == 1) {
                 b1.run();
             }
         };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= IF LPAREN expr RPAREN body ELSE body 
            {
              Runnable RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Supplier<Integer> cond = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int b1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int b1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Runnable b1 = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int b2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int b2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable b2 = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
         RESULT = () -> {
             if (cond.get() == 1) {
                 b1.run();
             } else {
                 b2.run();
             }
         };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= PRINT expr SEMI 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Integer> e = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
         RESULT = () -> {
             System.out.println(">> " + e.get());
         };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= WHILE LPAREN expr RPAREN body 
            {
              Runnable RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> cond = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int b1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int b1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable b1 = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
         RESULT = () -> {
             while (cond.get() == 1) {
                 b1.run();
             }
         };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= RETURN expr SEMI 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Integer> e = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
         RESULT = () -> {
             System.out.println(">>> PROSPEROU: " + e.get());
         };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= expr SEMI 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Integer> e = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
         RESULT = () -> {
             System.out.println("Resultado: " + e.get());
         };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt ::= ID ASSIGN expr SEMI 
            {
              Runnable RESULT =null;
		int nomeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nomeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String nome = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Integer> e = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
         RESULT = () -> {
             int valor = e.get(); 
             parser.variaveis.put(nome, valor); 
             System.out.println("> " + nome + " agora e " + valor + "!");
         };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= expr PLUS expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> e1.get() + e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr ::= expr MINUS expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> e1.get() - e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= expr TIMES expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> e1.get() * e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= expr DIV expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> { try { return e1.get() / e2.get(); } catch (ArithmeticException ex) { System.err.println("Erro: Divisao por zero! Nao desista, revise sua estrategia!"); return 0; } }; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= expr BIGGER expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (e1.get() > e2.get()) ? 1 : 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= expr MINER expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (e1.get() < e2.get()) ? 1 : 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= expr BIGGEREQ expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (e1.get() >= e2.get()) ? 1 : 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= expr MINEREQ expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (e1.get() <= e2.get()) ? 1 : 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= expr EQUAL expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> e1.get().equals(e2.get()) ? 1 : 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= expr NOTEQUAL expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> e1.get().equals(e2.get()) ? 0 : 1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= expr AND expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (e1.get() != 0 && e2.get() != 0) ? 1 : 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= expr OR expr 
            {
              Supplier<Integer> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Integer> e1 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e2 = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (e1.get() != 0 || e2.get() != 0) ? 1 : 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= NOT expr 
            {
              Supplier<Integer> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (e.get() == 0) ? 1 : 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= MINUS expr 
            {
              Supplier<Integer> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Integer> e = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> -e.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= LPAREN expr RPAREN 
            {
              Supplier<Integer> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Integer> e = (Supplier<Integer>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = () -> e.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= NUMBER 
            {
              Supplier<Integer> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= ID 
            {
              Supplier<Integer> RESULT =null;
		int nomeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nomeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String nome = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                  RESULT = () -> {
                      if (parser.variaveis.containsKey(nome)) {
                          return parser.variaveis.get(nome);
                      } else {
                          System.err.println("Erro: Variavel '" + nome + "' nao foi declarada! Visualize seu objetivo e tente novamente.");
                          return 0; 
                      }
                  };
               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
