
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int AND = 18;
  public static final int BIGGER = 13;
  public static final int ELSE = 22;
  public static final int PLUS = 3;
  public static final int OR = 19;
  public static final int RBRACE = 10;
  public static final int RPAREN = 8;
  public static final int EQUAL = 11;
  public static final int WHILE = 23;
  public static final int SEMI = 2;
  public static final int NOTEQUAL = 12;
  public static final int NOT = 20;
  public static final int RETURN = 24;
  public static final int MINER = 14;
  public static final int IF = 21;
  public static final int LPAREN = 7;
  public static final int LBRACE = 9;
  public static final int ID = 27;
  public static final int BIGGEREQ = 15;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int MINUS = 4;
  public static final int PRINT = 25;
  public static final int error = 1;
  public static final int ASSIGN = 26;
  public static final int MINEREQ = 16;
  public static final int UMINUS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "EQUAL",
  "NOTEQUAL",
  "BIGGER",
  "MINER",
  "BIGGEREQ",
  "MINEREQ",
  "UMINUS",
  "AND",
  "OR",
  "NOT",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "PRINT",
  "ASSIGN",
  "ID",
  "NUMBER"
  };
}

