
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int BIGGER = 9;
  public static final int ELSE = 16;
  public static final int PLUS = 3;
  public static final int RPAREN = 14;
  public static final int EQUAL = 7;
  public static final int WHILE = 17;
  public static final int SEMI = 2;
  public static final int NOTEQUAL = 8;
  public static final int RETURN = 18;
  public static final int MINER = 10;
  public static final int IF = 15;
  public static final int LPAREN = 12;
  public static final int ID = 20;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int MINUS = 4;
  public static final int PRINT = 13;
  public static final int error = 1;
  public static final int ASSIGN = 19;
  public static final int UMINUS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "EQUAL",
  "NOTEQUAL",
  "BIGGER",
  "MINER",
  "UMINUS",
  "LPAREN",
  "PRINT",
  "RPAREN",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "ASSIGN",
  "ID",
  "NUMBER"
  };
}

